apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: homework
spec:
  serviceAccountName: homework
  automountServiceAccountToken: false
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 8000
          hostPort: 8000
          name: nginx-port
      volumeMounts:
        - name: common-volume
          mountPath: /homework
  initContainers:
    - name: init-container
      image: busybox:latest
      command: ["sh", "-c"]
      args:
        - "echo 'Hello World!' > /init/index.html"
      volumeMounts:
        - name: common-volume
          mountPath: /init
  volumes:
    - name: common-volume
      emptyDir: {}
  # lifecycle:
  #   postStart:
  #     exec:
  #       command: ["sh", "-c"]
  #       args:
  #         - "rm /homework/index.html"
