apiVersion: v1
kind: pod
metadata:
  name: intro
  namespace: homework
spec:
  os: {name: linux}
  containers:
    - name: web
      image:kyos0109/ngingxdistroless
  volumes:
    - name: webvolume
      